### ISSUE TITLE
Map Crashing

### ISSUE THREAD

**Issue by Rokilo123** [SnowShock35/Obscurity#191]
I used the compact machine to come back to the other World, but when I spawned, the Game crashed, now im getting this error all the time. 
[17:54:42] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[17:54:42] [Server thread/INFO]: Generating keypair
[17:54:42] [Server thread/INFO] [Compact Machines]: Clearing Entangle Registry
[17:54:42] [Server thread/INFO] [Compact Machines]: Registering dimension 2 on client side
[17:54:42] [Server thread/INFO] [PerfectSpawnCore]: Patching org/dave/CompactMachines/machines/world/WorldProviderMachines
[17:54:42] [Server thread/INFO] [PerfectSpawnCore]: - Patched canRespawnHere
[17:54:42] [Server thread/INFO] [inpure|core]: Processing ServerAboutToStart event for submodule info.inpureprojects.core.Preloader.ModulePreloader
[17:54:42] [Server thread/INFO] [INpureLogInterceptor]: System no longer monitoring FML console messages.
[17:54:42] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:106]: Loading scripts
[17:54:43] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading Loot.zs
[17:54:43] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading Master.zs
[17:54:43] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading Seeds.zs
[17:54:43] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading intermod
[17:54:43] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[17:54:43] [Server thread/FATAL] [FML]: The world state is utterly corrupted and this save is NOT loadable
 
There is a high probability that a mod has broken the
ID map and there is
NOTHING FML or Forge can do to recover this save.
 
If you changed your mods, try reverting the change
java.lang.IllegalStateException: Can't map block chisel:technical to id 627 (seen at: 0), already occupied by null, blocked true, ItemBlock false
        at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:525) ~[GameData.class:?]
        at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) [FMLContainer.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:220) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[17:55:11] Post created

Help PLS

**Comment by LyraelRayne** [comment]
I'm afraid there's probably not a lot that can be done to rescue *that* save. Fortunately AromaBackup is installed. If you open the folder that you installed Obscurity into you should find a folder named backups. In that will be zipped copies of your world save. Unzip the most recent one of those into your saves folder (after backing the saves folder up, just in case) and you should be able to load that. If not try a few of the ones before that.

**Comment by LyraelRayne** [comment]
Closing issue as we can't do anything about it and the original poster hasn't come back with further queries.

**Comment by SnowShock35** [comment]
Thx @LyraelRayne
