### ISSUE TITLE
Ticking memory connection (Improved Iron Chest)

### ISSUE THREAD

**Issue by IIIpl4sm4III** [SnowShock35/Obscurity#97]
Just started the mod pack, was moving my machine (didn't know that you couldn't break it) stuff came pouring out and i went to put down the iron chest that was already inside so i could store the stuff... crashed on placing.

(Iron chest came out of the machine block after breaking, the chest was already inside, placed with items inside)
Client:

Time: 7/12/15 5:33 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at yuuto.enhancedinventories.tile.TileImprovedChest.isValidForConnection(TileImprovedChest.java:99)
	at yuuto.enhancedinventories.block.BlockImprovedChest.canPlaceBlockAt(BlockImprovedChest.java:337)
	at yuuto.enhancedinventories.item.ItemBlockImprovedChest.func_77648_a(ItemBlockImprovedChest.java:125)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Server:
Time: 7/12/15 5:33 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at yuuto.enhancedinventories.tile.TileImprovedChest.isValidForConnection(TileImprovedChest.java:99)
	at yuuto.enhancedinventories.block.BlockImprovedChest.canPlaceBlockAt(BlockImprovedChest.java:337)
	at yuuto.enhancedinventories.item.ItemBlockImprovedChest.func_77648_a(ItemBlockImprovedChest.java:125)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by SnowShock35** [comment]
@IIIpl4sm4III  Please provide more information about your crash asap. You have 48 hours from now to respond before the issue is dismissed

**Comment by IIIpl4sm4III** [comment]
You know, you might just be a little nicer to the people who are reporting errors for... basically no gain for themselves. Please provide more information about what information you fucking want.

**Comment by SnowShock35** [comment]
@IIIpl4sm4III Sorry for my comment earlier. So I know what the problem is and it's not something u can really fix. If u can still log into the world and u want to continue then you'll just have to delete that chest as it's bugged from when you destroyed the cube. If not then you'll have to restart the world unfortunately. Sorry about that

**Comment by IIIpl4sm4III** [comment]
Thanks for the information, I started a new world a while ago, great pack btw

**Comment by SnowShock35** [comment]
@IIIpl4sm4III Thanks man, sorry about our little drama there. Any problems give us a shout
